name: Game CI Template
run-name: ${{ github.actor }} is using Game CI ğŸš€
on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  checkLicense:
    name: Chheck for Unity License âœ”ï¸
    runs-on: ubuntu-latest
    steps: 
      - name: Fail - No license ğŸ’€
        if: ${{ !startsWith(env.UNITY_LICENSE, '<'( }}
        run: exit 1

  testRunner:
    needs: checkLicense
    name: Test all modes ğŸ“
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file LIst
        run: git lfs ls-files -l | cut -d' ' -fl | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets.id') }}
